"$schema" = "./node_modules/wrangler/config-schema.json"

# Change this if your existing Cloudflare Pages project uses a different slug.
name = "atlas-marchabilite-cyclabilite"
pages_build_output_dir = "./build"
compatibility_date = "2026-03-14"

[vars]
VITE_PM_TILES_WALK_SEGMENT = "https://pub-1aeb7e0af59940a9bf635336182c8eaa.r2.dev/walk_agglo_segment.pmtiles"
VITE_PM_TILES_URL = "https://pub-1aeb7e0af59940a9bf635336182c8eaa.r2.dev/walk_agglo_segment.pmtiles"
VITE_PM_TILES_CARREAU200 = "https://pub-1aeb7e0af59940a9bf635336182c8eaa.r2.dev/walk_agglo_carreau200.pmtiles"
VITE_PM_TILES_ZONETRAFIC = "https://pub-1aeb7e0af59940a9bf635336182c8eaa.r2.dev/walk_agglo_infracommunal.pmtiles"
VITE_PM_TILES_BIKE_SEGMENT = "https://pub-23cee30d1f03450dbc03f60446ae3cf6.r2.dev/bike_agglo_segment.pmtiles"
VITE_PM_TILES_BIKE_CARREAU200 = "https://pub-23cee30d1f03450dbc03f60446ae3cf6.r2.dev/bike_agglo_carreau200.pmtiles"
VITE_PM_TILES_BIKE_INFRACOMMUNAL = "https://pub-23cee30d1f03450dbc03f60446ae3cf6.r2.dev/bike_agglo_infracommunal.pmtiles"
VITE_PM_TILES_WALK_SEGMENT_CANTONGE = "https://pub-1aeb7e0af59940a9bf635336182c8eaa.r2.dev/walk_canton_segment.pmtiles"
VITE_PM_TILES_WALK_CARREAU200_CANTONGE = "https://pub-1aeb7e0af59940a9bf635336182c8eaa.r2.dev/walk_canton_carreau200.pmtiles"
VITE_PM_TILES_WALK_ZONETRAFIC_CANTONGE = "https://pub-1aeb7e0af59940a9bf635336182c8eaa.r2.dev/walk_canton_infracommunal.pmtiles"
VITE_PM_TILES_BIKE_SEGMENT_CANTONGE = "https://pub-23cee30d1f03450dbc03f60446ae3cf6.r2.dev/bike_canton_segment.pmtiles"
VITE_PM_TILES_BIKE_CARREAU200_CANTONGE = "https://pub-23cee30d1f03450dbc03f60446ae3cf6.r2.dev/bike_canton_carreau200.pmtiles"
VITE_PM_TILES_BIKE_INFRACOMMUNAL_CANTONGE = "https://pub-23cee30d1f03450dbc03f60446ae3cf6.r2.dev/bike_canton_infracommunal.pmtiles"
VITE_PM_TILES_PERIMETER = "https://pub-1aeb7e0af59940a9bf635336182c8eaa.r2.dev/canton_perimeter.pmtiles"
VITE_SEG_SOURCE_LAYER = "walknet"
VITE_WALK_SOURCE_LAYER = "walknet"
VITE_CAR_SOURCE_LAYER = "carreau200"
VITE_ZT_SOURCE_LAYER = "zone_trafic"
VITE_BIKE_SOURCE_LAYER = "bikenet"
VITE_BIKE_CAR_SOURCE_LAYER = "carreau200"
VITE_BIKE_INFRA_SOURCE_LAYER = "infra_communal"
VITE_PERIMETER_SOURCE_LAYER = "canton_perimeter"
VITE_MAP_STYLE_VOYAGER = "https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json"
VITE_MAP_STYLE_SWISS_LIGHT = "https://vectortiles.geo.admin.ch/styles/ch.swisstopo.lightbasemap.vt/style.json"
VITE_MAP_STYLE_SWISS_IMAGERY = "https://vectortiles.geo.admin.ch/styles/ch.swisstopo.imagerybasemap.vt/style.json"
