import { Cible } from '../types';

/**
 * Donnees mock minimales des points d'attention.
 *
 * Elles servent de fallback si aucun GeoJSON ou Google Sheet n'est configure.
 * Le jeu principal servi par defaut est maintenant /public/data/cibles.geojson.
 */
export const mockCibles: Cible[] = [
  {
    cible_id: 'PS_001',
    faisceau_id: 'plo_stjulien',
    faisceau_nom: 'Saint-Julien – PLO – Geneve',
    theme_principal: 'equipements',
    latitude: 46.1432,
    longitude: 6.0835,
    titre_affichage: 'Parking velo gare routiere St-Julien',
    sous_titre_affichage: 'Stationnement securise absent',
    question_cle: 'Le stationnement velo est-il suffisant au pole d echange ?',
    score_indice_calcule: 1.8,
    classe_indice_calcule: 'tres_faible',
  },
  {
    cible_id: 'PS_002',
    faisceau_id: 'plo_stjulien',
    faisceau_nom: 'Saint-Julien – PLO – Geneve',
    theme_principal: 'permeabilite_frontiere',
    latitude: 46.1505,
    longitude: 6.0955,
    titre_affichage: 'Passage frontiere Bardonnex',
    sous_titre_affichage: 'Franchissement critique',
    question_cle: 'Le passage frontalier est-il adapte aux cyclistes ?',
    score_indice_calcule: 1.9,
    classe_indice_calcule: 'tres_faible',
  },
  {
    cible_id: 'PS_003',
    faisceau_id: 'plo_stjulien',
    faisceau_nom: 'Saint-Julien – PLO – Geneve',
    theme_principal: 'intersections',
    latitude: 46.1548,
    longitude: 6.1005,
    titre_affichage: 'Carrefour Route de Saint-Julien / Bardonnex',
    question_cle: 'La traversee de ce carrefour est-elle securisee pour les cyclistes ?',
    score_indice_calcule: 2.8,
    classe_indice_calcule: 'faible',
  },
  {
    cible_id: 'PS_004',
    faisceau_id: 'plo_stjulien',
    faisceau_nom: 'Saint-Julien – PLO – Geneve',
    theme_principal: 'continuite',
    latitude: 46.168,
    longitude: 6.111,
    titre_affichage: 'Discontinuite Route de Saconnex-d Arve',
    sous_titre_affichage: 'Rupture de la piste cyclable',
    question_cle: 'La continuite cyclable est-elle assuree sur cet axe ?',
    score_indice_calcule: 2.2,
    classe_indice_calcule: 'faible',
  },
  {
    cible_id: 'PS_005',
    faisceau_id: 'plo_stjulien',
    faisceau_nom: 'Saint-Julien – PLO – Geneve',
    theme_principal: 'equipements',
    latitude: 46.1855,
    longitude: 6.133,
    titre_affichage: 'Station velo Carouge-Arve',
    sous_titre_affichage: 'Arceaux, pompe, reparation',
    question_cle: 'Les equipements sont-ils suffisants pour un pole multimodal ?',
    score_indice_calcule: 3.1,
    classe_indice_calcule: 'moyen',
  },
  {
    cible_id: 'TG_001',
    faisceau_id: 'thonex_gaillard',
    faisceau_nom: 'Gaillard – Thonex – Eaux-Vives',
    theme_principal: 'giratoires',
    latitude: 46.194,
    longitude: 6.231,
    titre_affichage: 'Giratoire Avenue de Gaillard',
    sous_titre_affichage: 'Giratoire primaire multi-voies',
    question_cle: 'Le giratoire est-il praticable a velo en securite ?',
    score_indice_calcule: 2.7,
    classe_indice_calcule: 'faible',
  },
  {
    cible_id: 'TG_002',
    faisceau_id: 'thonex_gaillard',
    faisceau_nom: 'Gaillard – Thonex – Eaux-Vives',
    theme_principal: 'permeabilite_frontiere',
    latitude: 46.1985,
    longitude: 6.222,
    titre_affichage: 'Passage frontiere Moillesulaz',
    question_cle: 'La permeabilite frontaliere est-elle suffisante pour les cyclistes ?',
    score_indice_calcule: 2.3,
    classe_indice_calcule: 'faible',
  },
  {
    cible_id: 'TG_003',
    faisceau_id: 'thonex_gaillard',
    faisceau_nom: 'Gaillard – Thonex – Eaux-Vives',
    theme_principal: 'continuite',
    latitude: 46.2005,
    longitude: 6.209,
    titre_affichage: 'Discontinuite Rue de Geneve / Thonex',
    sous_titre_affichage: 'Bande cyclable interrompue',
    question_cle: 'La continuite cyclable est-elle assuree le long de cet axe ?',
    score_indice_calcule: 2.5,
    classe_indice_calcule: 'faible',
  },
  {
    cible_id: 'TG_004',
    faisceau_id: 'thonex_gaillard',
    faisceau_nom: 'Gaillard – Thonex – Eaux-Vives',
    theme_principal: 'intersections',
    latitude: 46.2028,
    longitude: 6.194,
    titre_affichage: 'Carrefour Gradelle / Route de Chene',
    question_cle: 'La gestion de cette intersection est-elle securisee pour les cyclistes ?',
    score_indice_calcule: 3.1,
    classe_indice_calcule: 'moyen',
  },
  {
    cible_id: 'TG_005',
    faisceau_id: 'thonex_gaillard',
    faisceau_nom: 'Gaillard – Thonex – Eaux-Vives',
    theme_principal: 'alternatives',
    latitude: 46.2058,
    longitude: 6.163,
    titre_affichage: 'Jonction Eaux-Vives / lac',
    sous_titre_affichage: 'Raccordement au reseau genevois',
    question_cle: 'Le raccordement aux voies cyclables genevoises est-il lisible et continu ?',
    score_indice_calcule: 3.5,
    classe_indice_calcule: 'bon',
  },
];
