import { Cible } from '../types';

/**
 * Données mock des points d'attention.
 *
 * Pour importer depuis un Google Sheet publié en CSV, configurez l'URL
 * dans /src/app/utils/data-loader.ts (constante CIBLES_SHEETS_CSV_URL).
 * Voir aussi /src/app/DATA-SOURCES.md pour le guide complet.
 *
 * Colonnes obligatoires du tableur :
 *   cible_id | faisceau_id | faisceau_nom | theme_principal | latitude | longitude | titre_affichage | score | classe
 *
 * Colonnes facultatives :
 *   sous_titre_affichage | question_cle
 *
 * Valeurs possibles pour theme_principal :
 *   permeabilite_frontiere, intersections, giratoires, alternatives, continuite, equipements, attractivite
 *
 * Valeurs possibles pour classe :
 *   tres_faible, faible, moyen, bon, tres_bon
 */

export const mockCibles: Cible[] = [
  // ═══════════════════════════════════════════════════
  // CORRIDOR SUD : Saint-Julien – PLO – Genève
  // ═══════════════════════════════════════════════════

  {
    cible_id: 'PS_001',
    faisceau_id: 'plo_stjulien',
    faisceau_nom: 'Saint-Julien – PLO – Genève',
    theme_principal: 'equipements',
    latitude: 46.1432,
    longitude: 6.0835,
    titre_affichage: 'Parking vélo gare routière St-Julien',
    sous_titre_affichage: 'Stationnement sécurisé absent',
    question_cle: 'Le stationnement vélo est-il sécurisé et en quantité suffisante au pôle d\'échange ?',
    score_indice_calcule: 1.8,
    classe_indice_calcule: 'tres_faible',
  },
  {
    cible_id: 'PS_002',
    faisceau_id: 'plo_stjulien',
    faisceau_nom: 'Saint-Julien – PLO – Genève',
    theme_principal: 'giratoires',
    latitude: 46.1405,
    longitude: 6.0790,
    titre_affichage: 'Giratoire Route de Norcier',
    sous_titre_affichage: 'Giratoire complexe multi-branches',
    question_cle: 'Le giratoire est-il praticable à vélo de manière fluide et sécurisée ?',
    score_indice_calcule: 3.2,
    classe_indice_calcule: 'moyen',
  },
  {
    cible_id: 'PS_003',
    faisceau_id: 'plo_stjulien',
    faisceau_nom: 'Saint-Julien – PLO – Genève',
    theme_principal: 'permeabilite_frontiere',
    latitude: 46.1505,
    longitude: 6.0955,
    titre_affichage: 'Passage frontière Bardonnex',
    sous_titre_affichage: 'Point de franchissement critique',
    question_cle: 'Le passage frontalier est-il adapté et lisible pour les cyclistes ?',
    score_indice_calcule: 1.9,
    classe_indice_calcule: 'tres_faible',
  },
  {
    cible_id: 'PS_004',
    faisceau_id: 'plo_stjulien',
    faisceau_nom: 'Saint-Julien – PLO – Genève',
    theme_principal: 'intersections',
    latitude: 46.1548,
    longitude: 6.1005,
    titre_affichage: 'Carrefour Route de Saint-Julien / Bardonnex',
    question_cle: 'La traversée de ce carrefour est-elle sécurisée pour les cyclistes ?',
    score_indice_calcule: 2.8,
    classe_indice_calcule: 'faible',
  },
  {
    cible_id: 'PS_005',
    faisceau_id: 'plo_stjulien',
    faisceau_nom: 'Saint-Julien – PLO – Genève',
    theme_principal: 'attractivite',
    latitude: 46.1610,
    longitude: 6.1060,
    titre_affichage: 'Chemin de campagne Compesières',
    sous_titre_affichage: 'Itinéraire rural transfrontalier',
    question_cle: 'Cet itinéraire rural offre-t-il une alternative attractive au réseau routier ?',
    score_indice_calcule: 3.3,
    classe_indice_calcule: 'moyen',
  },
  {
    cible_id: 'PS_006',
    faisceau_id: 'plo_stjulien',
    faisceau_nom: 'Saint-Julien – PLO – Genève',
    theme_principal: 'permeabilite_frontiere',
    latitude: 46.1585,
    longitude: 6.1030,
    titre_affichage: 'Passage Chemin de Thairy',
    question_cle: 'Ce passage secondaire est-il praticable et signalé ?',
    score_indice_calcule: 3.4,
    classe_indice_calcule: 'bon',
  },
  {
    cible_id: 'PS_007',
    faisceau_id: 'plo_stjulien',
    faisceau_nom: 'Saint-Julien – PLO – Genève',
    theme_principal: 'continuite',
    latitude: 46.1680,
    longitude: 6.1110,
    titre_affichage: 'Discontinuité Route de Saconnex-d\'Arve',
    sous_titre_affichage: 'Rupture majeure de la piste cyclable',
    question_cle: 'La continuité cyclable est-elle assurée sur ce segment ?',
    score_indice_calcule: 2.2,
    classe_indice_calcule: 'faible',
  },
  {
    cible_id: 'PS_008',
    faisceau_id: 'plo_stjulien',
    faisceau_nom: 'Saint-Julien – PLO – Genève',
    theme_principal: 'alternatives',
    latitude: 46.1650,
    longitude: 6.1150,
    titre_affichage: 'Alternative Chemin des Hutins',
    question_cle: 'Cette alternative constitue-t-elle un itinéraire viable et confortable ?',
    score_indice_calcule: 3.5,
    classe_indice_calcule: 'bon',
  },
  {
    cible_id: 'PS_009',
    faisceau_id: 'plo_stjulien',
    faisceau_nom: 'Saint-Julien – PLO – Genève',
    theme_principal: 'intersections',
    latitude: 46.1790,
    longitude: 6.1230,
    titre_affichage: 'Échangeur Bachet-de-Pesay',
    sous_titre_affichage: 'Noeud routier complexe',
    question_cle: 'Les cyclistes peuvent-ils traverser cet échangeur en sécurité ?',
    score_indice_calcule: 2.1,
    classe_indice_calcule: 'faible',
  },
  {
    cible_id: 'PS_010',
    faisceau_id: 'plo_stjulien',
    faisceau_nom: 'Saint-Julien – PLO – Genève',
    theme_principal: 'equipements',
    latitude: 46.1855,
    longitude: 6.1330,
    titre_affichage: 'Station vélo Carouge-Arve',
    sous_titre_affichage: 'Arceaux, pompe, réparation',
    question_cle: 'Les équipements sont-ils suffisants pour un pôle multimodal ?',
    score_indice_calcule: 3.1,
    classe_indice_calcule: 'moyen',
  },

  // ═══════════════════════════════════════════════════
  // CORRIDOR EST : Gaillard – Thonex – Eaux-Vives
  // ═══════════════════════════════════════════════════

  {
    cible_id: 'TG_001',
    faisceau_id: 'thonex_gaillard',
    faisceau_nom: 'Gaillard – Thonex – Eaux-Vives',
    theme_principal: 'giratoires',
    latitude: 46.1940,
    longitude: 6.2310,
    titre_affichage: 'Giratoire Avenue de Gaillard',
    sous_titre_affichage: 'Giratoire primaire multi-voies',
    question_cle: 'Le giratoire est-il praticable à vélo en sécurité ?',
    score_indice_calcule: 2.7,
    classe_indice_calcule: 'faible',
  },
  {
    cible_id: 'TG_002',
    faisceau_id: 'thonex_gaillard',
    faisceau_nom: 'Gaillard – Thonex – Eaux-Vives',
    theme_principal: 'attractivite',
    latitude: 46.1955,
    longitude: 6.2270,
    titre_affichage: 'Voie verte Foron',
    sous_titre_affichage: 'Tronçon paysager le long du Foron',
    question_cle: 'L\'itinéraire est-il suffisamment attractif pour attirer de nouveaux cyclistes ?',
    score_indice_calcule: 3.6,
    classe_indice_calcule: 'bon',
  },
  {
    cible_id: 'TG_003',
    faisceau_id: 'thonex_gaillard',
    faisceau_nom: 'Gaillard – Thonex – Eaux-Vives',
    theme_principal: 'permeabilite_frontiere',
    latitude: 46.1985,
    longitude: 6.2220,
    titre_affichage: 'Passage frontière Moillesulaz',
    question_cle: 'La perméabilité frontalière est-elle suffisante pour les cyclistes ?',
    score_indice_calcule: 2.3,
    classe_indice_calcule: 'faible',
  },
  {
    cible_id: 'TG_004',
    faisceau_id: 'thonex_gaillard',
    faisceau_nom: 'Gaillard – Thonex – Eaux-Vives',
    theme_principal: 'continuite',
    latitude: 46.2005,
    longitude: 6.2090,
    titre_affichage: 'Discontinuité Rue de Genève / Thonex',
    sous_titre_affichage: 'Bande cyclable interrompue',
    question_cle: 'La continuité cyclable est-elle assurée le long de cet axe ?',
    score_indice_calcule: 2.5,
    classe_indice_calcule: 'faible',
  },
  {
    cible_id: 'TG_005',
    faisceau_id: 'thonex_gaillard',
    faisceau_nom: 'Gaillard – Thonex – Eaux-Vives',
    theme_principal: 'equipements',
    latitude: 46.2015,
    longitude: 6.2040,
    titre_affichage: 'Station vélo Thonex-Moillesulaz',
    sous_titre_affichage: 'Arceaux, pompe, éclairage',
    question_cle: 'Les équipements sont-ils suffisants pour les pendulaires transfrontaliers ?',
    score_indice_calcule: 2.9,
    classe_indice_calcule: 'moyen',
  },
  {
    cible_id: 'TG_006',
    faisceau_id: 'thonex_gaillard',
    faisceau_nom: 'Gaillard – Thonex – Eaux-Vives',
    theme_principal: 'intersections',
    latitude: 46.2028,
    longitude: 6.1940,
    titre_affichage: 'Carrefour Gradelle / Route de Chêne',
    question_cle: 'La gestion de cette intersection est-elle sécurisée pour les cyclistes ?',
    score_indice_calcule: 3.1,
    classe_indice_calcule: 'moyen',
  },
  {
    cible_id: 'TG_007',
    faisceau_id: 'thonex_gaillard',
    faisceau_nom: 'Gaillard – Thonex – Eaux-Vives',
    theme_principal: 'alternatives',
    latitude: 46.2035,
    longitude: 6.1870,
    titre_affichage: 'Itinéraire Chemin de la Montagne',
    question_cle: 'Cette alternative est-elle attractive et bien signalée ?',
    score_indice_calcule: 3.8,
    classe_indice_calcule: 'bon',
  },
  {
    cible_id: 'TG_008',
    faisceau_id: 'thonex_gaillard',
    faisceau_nom: 'Gaillard – Thonex – Eaux-Vives',
    theme_principal: 'giratoires',
    latitude: 46.2048,
    longitude: 6.1760,
    titre_affichage: 'Giratoire Place de Chêne-Bougeries',
    question_cle: 'Le giratoire permet-il un passage cycliste fluide et sécurisé ?',
    score_indice_calcule: 2.4,
    classe_indice_calcule: 'faible',
  },
  {
    cible_id: 'TG_009',
    faisceau_id: 'thonex_gaillard',
    faisceau_nom: 'Gaillard – Thonex – Eaux-Vives',
    theme_principal: 'continuite',
    latitude: 46.2058,
    longitude: 6.1630,
    titre_affichage: 'Route de Chêne – section Villereuse',
    question_cle: 'Un aménagement cyclable continu est-il possible sur cet axe ?',
    score_indice_calcule: 2.6,
    classe_indice_calcule: 'faible',
  },
  {
    cible_id: 'TG_010',
    faisceau_id: 'thonex_gaillard',
    faisceau_nom: 'Gaillard – Thonex – Eaux-Vives',
    theme_principal: 'permeabilite_frontiere',
    latitude: 46.2065,
    longitude: 6.1530,
    titre_affichage: 'Jonction Eaux-Vives / Lac',
    question_cle: 'Le raccordement aux voies cyclables genevoises est-il lisible et continu ?',
    score_indice_calcule: 3.5,
    classe_indice_calcule: 'bon',
  },
];